"use client"

import * as React from "react"
import { DirectionProvider } from "@base-ui/react/direction-provider"
import { createStoredValue } from "@/lib/use-stored"

export type Lang = "ar" | "en"

/** A bilingual string. Data (courses, alerts, explanations) carries both languages. */
export type L = { ar: string; en: string }

const dict = {
  appName: { ar: "مساري", en: "Masari" },
  appTagline: { ar: "مرشدك الأكاديمي الذكي", en: "Your AI academic advisor" },
  navDashboard: { ar: "الرئيسية", en: "Dashboard" },
  navChat: { ar: "اسأل مساري", en: "Ask Masari" },
  navCourses: { ar: "التوصيات", en: "Recommendations" },
  navPlan: { ar: "الخطة الدراسية", en: "Study plan" },
  demoData: { ar: "بيانات تجريبية", en: "Demo data" },
  demoDataHint: {
    ar: "المقررات واللائحة من دليل برنامج AIE، لكن الطالب والدكاترة والمقاعد بيانات تجريبية. مش مربوط بنظام الجامعة.",
    en: "Courses and regulations come from the AIE Program Guide; the student, instructors and seats are simulated. Not connected to a university system.",
  },
  switchLang: { ar: "English", en: "العربية" },
  toggleTheme: { ar: "تبديل الوضع الليلي", en: "Toggle dark mode" },
  openMenu: { ar: "فتح القائمة", en: "Open menu" },

  verified: { ar: "تم التحقق بالقواعد", en: "Rule-verified" },
  verifiedHint: {
    ar: "نتيجة حتمية من محرك القواعد الأكاديمية، وليست من نموذج اللغة.",
    en: "Deterministic result from the academic rules engine, not from the language model.",
  },
  aiExplanation: { ar: "شرح بالذكاء الاصطناعي", en: "AI explanation" },
  aiExplanationHint: {
    ar: "صياغة نموذج اللغة لشرح النتيجة. القرار نفسه مأخوذ من القواعد والبيانات.",
    en: "Wording generated by the language model. The decision itself comes from rules and data.",
  },
  source: { ar: "المصدر", en: "Source" },
  confidence: { ar: "الثقة", en: "Confidence" },
  confHigh: { ar: "عالية", en: "High" },
  confMedium: { ar: "متوسطة", en: "Medium" },
  confLow: { ar: "منخفضة", en: "Low" },
  responses: { ar: "تقييم", en: "responses" },
  creditHours: { ar: "ساعة معتمدة", en: "credit hours" },
  creditsShort: { ar: "س.م", en: "cr" },

  // Dashboard
  greeting: { ar: "أهلاً", en: "Welcome back" },
  dashSubtitle: {
    ar: "دي نظرة سريعة على موقفك الأكاديمي والخطوة الجاية.",
    en: "Here is a quick view of your academic standing and what comes next.",
  },
  gpa: { ar: "المعدل التراكمي", en: "Cumulative GPA" },
  earned: { ar: "الساعات المكتسبة", en: "Credits earned" },
  remaining: { ar: "الساعات المتبقية", en: "Credits remaining" },
  level: { ar: "المستوى", en: "Level" },
  maxLoad: { ar: "الحد الأقصى للتسجيل", en: "Max registration load" },
  gradProgress: { ar: "التقدم نحو التخرج", en: "Graduation progress" },
  gradProgressDesc: {
    ar: "محسوب من سجلك مقابل متطلبات اللائحة",
    en: "Computed from your record against the bylaw requirements",
  },
  alerts: { ar: "تنبيهات أكاديمية", en: "Academic alerts" },
  nextSemester: { ar: "مقترح الفصل القادم", en: "Next semester proposal" },
  viewAll: { ar: "عرض الكل", en: "View all" },
  askMasari: { ar: "اسأل مساري", en: "Ask Masari" },
  estGraduation: { ar: "التخرج المتوقع", en: "Estimated graduation" },
  of: { ar: "من", en: "of" },

  // Chat
  chatTitle: { ar: "محادثة مع مساري", en: "Chat with Masari" },
  chatPlaceholder: {
    ar: "اسأل عن مقرر، لائحة، أو خطتك الدراسية…",
    en: "Ask about a course, a regulation, or your study plan…",
  },
  send: { ar: "إرسال", en: "Send" },
  voiceInput: { ar: "إدخال صوتي", en: "Voice input" },
  listening: { ar: "بيسمعك… (عربي / English)", en: "Listening… (Arabic / English)" },
  stopListening: { ar: "إيقاف التسجيل", en: "Stop recording" },
  suggestions: { ar: "اقتراحات", en: "Suggestions" },
  contextPanel: { ar: "اللي مساري عارفه عنك", en: "What Masari knows" },
  sourcesUsed: { ar: "المصادر المستخدمة", en: "Sources used" },
  demoReply: {
    ar: "دي نسخة تجريبية من الواجهة. الرد الحقيقي هييجي من الـ backend (RAG + محرك القواعد + نموذج التوصيات) بعد ربطه.",
    en: "This is a UI prototype. Real answers will come from the backend (RAG + rules engine + recommendation model) once it is connected.",
  },
  newChat: { ar: "محادثة جديدة", en: "New chat" },
  ragSources: { ar: "المصادر اللي اتبحث فيها", en: "Sources searched" },
  chatError: {
    ar: "مساري مش قادر يرد دلوقتي. اتأكد إن خدمة الـ AI شغالة وجرب تاني كمان شوية.",
    en: "Masari can't answer right now. Make sure the AI service is running and try again shortly.",
  },

  // Recommendations
  recTitle: { ar: "توصيات المقررات والمحاضرين", en: "Course & instructor recommendations" },
  recSubtitle: {
    ar: "بنستبعد الأول المقررات غير المسموح بيها، وبعدين نرتب الباقي حسب مناسبتها ليك.",
    en: "Ineligible courses are filtered out first, then the rest are ranked by how well they suit you.",
  },
  tabCourses: { ar: "المقررات", en: "Courses" },
  tabInstructors: { ar: "المحاضرون", en: "Instructors" },
  selectedLoad: { ar: "الحمل المختار", en: "Selected load" },
  loadOk: { ar: "داخل الحد المسموح", en: "Within the allowed limit" },
  loadOver: { ar: "تجاوز الحد المسموح", en: "Exceeds the allowed limit" },
  rank: { ar: "الترتيب", en: "Rank" },
  priority: { ar: "الأولوية", en: "Priority" },
  unlocks: { ar: "يفتح", en: "Unlocks" },
  coursesWord: { ar: "مقررات", en: "courses" },
  prereqsMet: { ar: "المتطلبات السابقة مستوفاة", en: "Prerequisites met" },
  whyRecommended: { ar: "ليه بنرشحه؟", en: "Why recommended?" },
  addToPlan: { ar: "إضافة للجدول", en: "Add to schedule" },
  added: { ar: "مضاف", en: "Added" },
  notEligible: { ar: "غير مؤهل حاليًا", en: "Not eligible yet" },
  missingPrereq: { ar: "متطلب ناقص", en: "Missing prerequisite" },
  seats: { ar: "مقاعد", en: "seats" },
  full: { ar: "مكتمل", en: "Full" },
  requestSeat: { ar: "طلب فتح مقعد", en: "Request a seat" },
  forCourse: { ar: "المقرر", en: "Course" },
  compatibility: { ar: "التوافق معك", en: "Compatibility with you" },
  yourPreferences: { ar: "تفضيلاتك", en: "Your preferences" },
  prefsHint: {
    ar: "غيّر التفضيلات وشوف الترتيب بيتغير إزاي.",
    en: "Adjust your preferences and watch the ranking update.",
  },
  demoScoring: {
    ar: "حساب توضيحي مؤقت، هيتبدل بنموذج التوافق الفعلي.",
    en: "Placeholder scoring. To be replaced by the trained compatibility model.",
  },
  youPrefer: { ar: "تفضيلك", en: "Your preference" },
  limitedData: {
    ar: "البيانات محدودة، فخد التوصية دي بحذر.",
    en: "Limited data. Treat this suggestion with caution.",
  },
  bestMatch: { ar: "الأنسب ليك", en: "Best match" },
  prefPace: { ar: "سرعة الشرح المفضلة", en: "Preferred teaching pace" },
  prefWorkload: { ar: "العبء اللي تقدر تتحمله", en: "Workload you can handle" },
  prefPractical: { ar: "عملي ولا نظري", en: "Practical or theoretical" },
  slow: { ar: "هادية", en: "Slow" },
  fast: { ar: "سريعة", en: "Fast" },
  light: { ar: "خفيف", en: "Light" },
  heavy: { ar: "تقيل", en: "Heavy" },
  theoretical: { ar: "نظري", en: "Theoretical" },
  practical: { ar: "عملي", en: "Practical" },
  sectionSeats: { ar: "المقاعد حسب السكشن", en: "Seats by section" },
  scoreOutOf: { ar: "درجة الأولوية من 100", en: "Priority score out of 100" },
  section: { ar: "سكشن", en: "Section" },

  // Plan
  planTitle: { ar: "الخطة الدراسية", en: "Study plan" },
  planSubtitle: {
    ar: "خطة مقترحة للفصول الجاية، متحققة من المتطلبات السابقة وحدود الساعات.",
    en: "A proposed multi-semester plan, checked against prerequisites and credit limits.",
  },
  whatIf: { ar: "ماذا لو؟", en: "What if?" },
  whatIfDesc: {
    ar: "جرّب سيناريو وشوف تأثيره على خطتك وموعد تخرجك.",
    en: "Try a scenario and see its impact on your plan and graduation date.",
  },
  baseline: { ar: "الخطة الحالية", en: "Current plan" },
  scenario: { ar: "السيناريو", en: "Scenario" },
  impact: { ar: "التأثير", en: "Impact" },
  affected: { ar: "مقررات متأثرة", en: "Affected courses" },
  electives: { ar: "متابعة الاختياري", en: "Elective tracking" },
  semesterLoad: { ar: "حمل الفصل", en: "Semester load" },
  requires: { ar: "يتطلب", en: "Requires" },
  delayed: { ar: "اتأخر", en: "Delayed" },
  movedEarlier: { ar: "اتقدّم", en: "Moved earlier" },
  noChange: { ar: "بدون تغيير", en: "No change" },
  reset: { ar: "رجوع للخطة الحالية", en: "Reset to current plan" },
  underMinLoad: {
    ar: "أقل من الحد الأدنى (12 ساعة). مسموح بس في ترم التخرج أو بموافقة المجلس.",
    en: "Below the 12-credit minimum. Allowed only in the graduation term or with council approval.",
  },
  noCoursesThisTerm: { ar: "مفيش مقررات متاحة الترم ده حسب الخطة.", en: "No courses available this term under the plan." },

  // Course catalog
  navCatalog: { ar: "دليل المقررات", en: "Course catalog" },
  navCatalogShort: { ar: "الدليل", en: "Catalog" },
  navChatShort: { ar: "اسأل", en: "Ask" },
  navCoursesShort: { ar: "التوصيات", en: "For you" },
  navPlanShort: { ar: "الخطة", en: "Plan" },
  mainNav: { ar: "التنقل الرئيسي", en: "Main navigation" },
  pathTitle: { ar: "مسارك للتخرج", en: "Your path to graduation" },
  pathAria: {
    ar: "مسارك: الفصول المكتملة، ثم الأترام المخططة لحد التخرج.",
    en: "Your path: completed semesters, then planned terms up to graduation.",
  },
  graduation: { ar: "التخرج", en: "Graduation" },
  pathEmpty: { ar: "ترم فاضي", en: "Empty term" },
  youAreHere: { ar: "إنت هنا", en: "You are here" },
  semShort: { ar: "الفصل", en: "Sem" },
  pathSwipe: { ar: "اسحب يمين وشمال عشان تشوف كل الفصول", en: "Swipe sideways to see every semester" },
  pathHasFail: { ar: "فصل فيه رسوب", en: "Semester with a failed course" },
  pathLegendDone: { ar: "فصل مكتمل", en: "Completed semester" },
  pathLegendPlanned: { ar: "ترم مخطط", en: "Planned term" },
  pathLegendEmpty: { ar: "ترم مفيهوش مقررات متاحة", en: "Term with no available courses" },
  standing: { ar: "موقفك الأكاديمي", en: "Academic standing" },
  studentProfile: { ar: "ملف الطالب", en: "Student profile" },
  skipToContent: { ar: "تخطي للمحتوى", en: "Skip to content" },
  switchLangLabel: { ar: "التبديل للإنجليزية", en: "Switch to Arabic" },
  catalogTitle: { ar: "دليل مقررات هندسة الذكاء الاصطناعي", en: "AI Engineering course catalog" },
  catalogSubtitle: {
    ar: "كل مقررات البرنامج ومتطلباتها السابقة، ومعاها حالتك في كل مقرر.",
    en: "Every course in the program with its prerequisites, plus your status in each.",
  },
  tabCatalogCourses: { ar: "المقررات والمتطلبات", en: "Courses & prerequisites" },
  tabRegulations: { ar: "اللائحة", en: "Regulations" },
  statTotalCredits: { ar: "إجمالي الساعات", en: "Total credits" },
  statCourses: { ar: "مقرر في الخطة", en: "Courses in the plan" },
  statElectiveSlots: { ar: "خانات اختياري", en: "Elective slots" },
  statSemesters: { ar: "فصول دراسية", en: "Semesters" },
  universityReq: { ar: "متطلبات جامعة", en: "University req." },
  collegeReq: { ar: "متطلبات كلية", en: "College req." },
  specializationReq: { ar: "متطلبات تخصص", en: "Specialization" },
  perBylaws: { ar: "حسب اللائحة", en: "Per the bylaws" },
  search: { ar: "بحث", en: "Search" },
  searchPlaceholder: { ar: "كود أو اسم المقرر…", en: "Code or course name…" },
  levelLabel: { ar: "المستوى", en: "Level" },
  semesterLabel: { ar: "الفصل", en: "Semester" },
  departmentLabel: { ar: "القسم", en: "Department" },
  typeLabel: { ar: "النوع", en: "Type" },
  termLabel: { ar: "الترم", en: "Term" },
  statusLabel: { ar: "حالتي", en: "My status" },
  all: { ar: "الكل", en: "All" },
  fall: { ar: "خريف", en: "Fall" },
  spring: { ar: "ربيع", en: "Spring" },
  stPassed: { ar: "ناجح", en: "Passed" },
  stFailed: { ar: "راسب", en: "Failed" },
  stEligible: { ar: "مؤهل", en: "Eligible" },
  stLocked: { ar: "مقفول", en: "Locked" },
  resetFilters: { ar: "مسح الفلاتر", en: "Reset filters" },
  showing: { ar: "عرض", en: "Showing" },
  noResults: { ar: "مفيش مقررات مطابقة للفلاتر دي.", en: "No courses match these filters." },
  prerequisites: { ar: "المتطلبات السابقة", en: "Prerequisites" },
  none: { ar: "لا يوجد", en: "None" },
  requiredBy: { ar: "متطلب سابق لـ", en: "Prerequisite for" },
  slotOptions: { ar: "المقررات المتاحة للخانة دي", en: "Courses for this slot" },
  yourPick: { ar: "اختيارك", en: "Your pick" },
  minEarned: { ar: "ساعة مكتسبة على الأقل", en: "earned credits minimum" },
  short: { ar: "ناقص", en: "Short by" },
  details: { ar: "التفاصيل", en: "Details" },
  colCode: { ar: "الكود", en: "Code" },
  colName: { ar: "المقرر", en: "Course" },
  statusHint: {
    ar: "حالتك محسوبة بمحرك القواعد من سجلك (طالب تجريبي).",
    en: "Your status is computed by the rules engine from your record (demo student).",
  },
  catalogSource: {
    ar: "المصدر: دليل برنامج AIE، وهو ملخص غير رسمي للائحة. راجع اللائحة الرسمية قبل الاعتماد عليه.",
    en: "Source: the AIE Program Guide, an unofficial summary of the bylaws. Check the official bylaws before relying on it.",
  },
  yourLimit: { ar: "حدّك", en: "Your limit" },
  gradeScaleTitle: { ar: "نظام التقديرات", en: "Grading scale" },
  gradeCol: { ar: "التقدير", en: "Grade" },
  pointsCol: { ar: "النقاط", en: "Points" },
  assessmentTitle: { ar: "توزيع الدرجات", en: "Grade distribution" },
} satisfies Record<string, L>

export type DictKey = keyof typeof dict

type I18nContextValue = {
  lang: Lang
  dir: "rtl" | "ltr"
  setLang: (l: Lang) => void
  t: (key: DictKey) => string
  tr: (value: L) => string
  num: (n: number, opts?: Intl.NumberFormatOptions) => string
}

const I18nContext = React.createContext<I18nContextValue | null>(null)
const useStoredLang = createStoredValue<Lang>("masari.lang", "ar", (v): v is Lang => v === "ar" || v === "en")

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useStoredLang()

  React.useEffect(() => {
    const el = document.documentElement
    el.lang = lang
    el.dir = lang === "ar" ? "rtl" : "ltr"
    // The pre-paint script in layout.tsx hides the Arabic prerender while English loads.
    if (lang === "en") el.removeAttribute("data-lang-pending")
  }, [lang])

  const value = React.useMemo<I18nContextValue>(() => {
    // Western digits in both languages, matching common usage in Egyptian university records.
    const locale = lang === "ar" ? "ar-EG-u-nu-latn" : "en-US"
    return {
      lang,
      dir: lang === "ar" ? "rtl" : "ltr",
      setLang,
      t: (key) => dict[key][lang],
      tr: (v) => v[lang],
      num: (n, opts) => new Intl.NumberFormat(locale, opts).format(n),
    }
  }, [lang, setLang])

  return (
    <I18nContext.Provider value={value}>
      {/* Tells Base UI components (slider, menus, tabs) which way to read. */}
      <DirectionProvider direction={value.dir}>{children}</DirectionProvider>
    </I18nContext.Provider>
  )
}

export function useI18n() {
  const ctx = React.useContext(I18nContext)
  if (!ctx) throw new Error("useI18n must be used inside <I18nProvider>")
  return ctx
}
