"use client"

import * as React from "react"
import { DirectionProvider } from "@base-ui/react/direction-provider"
import { createStoredValue } from "@/lib/use-stored"

export type Lang = "ar" | "en"

/** A bilingual string. Data (courses, alerts, explanations) carries both languages. */
export type L = { ar: string; en: string }

const dict = {
  appName: { ar: "مساري", en: "Masari" },
  appTagline: { ar: "مرشدك الأكاديمي الذكي", en: "Your AI academic advisor" },
  navDashboard: { ar: "الرئيسية", en: "Dashboard" },
  navChat: { ar: "اسأل مساري", en: "Ask Masari" },
  navCourses: { ar: "التوصيات", en: "Recommendations" },
  navPlan: { ar: "خطة التخرج", en: "Graduation plan" },
  demoData: { ar: "بيانات تجريبية", en: "Demo data" },
  demoDataHint: {
    ar: "المقررات واللائحة من دليل برنامج AIE، لكن الطالب والدكاترة والمقاعد بيانات تجريبية. مش مربوط بنظام الجامعة.",
    en: "Courses and regulations come from the AIE Program Guide; the student, instructors and seats are simulated. Not connected to a university system.",
  },
  switchLang: { ar: "English", en: "العربية" },
  academicCalendar: { ar: "التقويم الأكاديمي", en: "Academic calendar" },
  openFullSize: { ar: "افتح الصورة بالحجم الكامل", en: "Open full size" },
  toggleTheme: { ar: "تبديل الوضع الليلي", en: "Toggle dark mode" },
  openMenu: { ar: "فتح القائمة", en: "Open menu" },

  verified: { ar: "تم التحقق بالقواعد", en: "Rule-verified" },
  verifiedHint: {
    ar: "نتيجة حتمية من محرك القواعد الأكاديمية، وليست من نموذج اللغة.",
    en: "Deterministic result from the academic rules engine, not from the language model.",
  },
  aiExplanation: { ar: "شرح بالذكاء الاصطناعي", en: "AI explanation" },
  aiExplanationHint: {
    ar: "صياغة نموذج اللغة لشرح النتيجة. القرار نفسه مأخوذ من القواعد والبيانات.",
    en: "Wording generated by the language model. The decision itself comes from rules and data.",
  },
  source: { ar: "المصدر", en: "Source" },
  confidence: { ar: "الثقة", en: "Confidence" },
  confHigh: { ar: "عالية", en: "High" },
  confMedium: { ar: "متوسطة", en: "Medium" },
  confLow: { ar: "منخفضة", en: "Low" },
  responses: { ar: "تقييم", en: "responses" },
  creditHours: { ar: "ساعة معتمدة", en: "credit hours" },
  creditsShort: { ar: "س.م", en: "cr" },

  // Dashboard
  greeting: { ar: "أهلاً", en: "Welcome back" },
  dashSubtitle: {
    ar: "دي نظرة سريعة على موقفك الأكاديمي والخطوة الجاية.",
    en: "Here is a quick view of your academic standing and what comes next.",
  },
  gpa: { ar: "المعدل التراكمي", en: "Cumulative GPA" },
  earned: { ar: "الساعات المكتسبة", en: "Credits earned" },
  remaining: { ar: "الساعات المتبقية", en: "Credits remaining" },
  level: { ar: "المستوى", en: "Level" },
  maxLoad: { ar: "الحد الأقصى للتسجيل", en: "Max registration load" },
  gradProgress: { ar: "التقدم نحو التخرج", en: "Graduation progress" },
  gradProgressDesc: {
    ar: "محسوب من سجلك مقابل متطلبات اللائحة",
    en: "Computed from your record against the bylaw requirements",
  },
  alerts: { ar: "تنبيهات أكاديمية", en: "Academic alerts" },
  noAlerts: { ar: "مفيش تنبيهات دلوقتي.", en: "No alerts right now." },
  nextSemester: { ar: "مقترح الفصل الحالي", en: "This semester's proposal" },
  viewAll: { ar: "عرض الكل", en: "View all" },
  askMasari: { ar: "اسأل مساري", en: "Ask Masari" },
  estGraduation: { ar: "التخرج المتوقع", en: "Estimated graduation" },
  of: { ar: "من", en: "of" },

  // Chat
  chatTitle: { ar: "محادثة مع مساري", en: "Chat with Masari" },
  chatPlaceholder: {
    ar: "اسأل عن مقرر، لائحة، أو خطتك الدراسية…",
    en: "Ask about a course, a regulation, or your study plan…",
  },
  send: { ar: "إرسال", en: "Send" },
  voiceInput: { ar: "إدخال صوتي", en: "Voice input" },
  listening: { ar: "بيسمعك… (عربي / English)", en: "Listening… (Arabic / English)" },
  stopListening: { ar: "إيقاف التسجيل", en: "Stop recording" },
  transcribing: { ar: "بحوّل صوتك لكلام…", en: "Turning your voice into text…" },
  micPermission: {
    ar: "مساري محتاج إذن الميكروفون. اسمح بيه من علامة القفل جنب عنوان الموقع وجرب تاني.",
    en: "Masari needs microphone access. Allow it from the lock icon next to the address and try again.",
  },
  micUnsupported: { ar: "المتصفح ده مش بيدعم التسجيل. جرب Chrome أو Edge.", en: "This browser can't record audio. Try Chrome or Edge." },
  micError: { ar: "مقدرتش أفهم التسجيل. جرب تاني أو اكتب سؤالك.", en: "Couldn't transcribe that. Try again or type your question." },
  suggestions: { ar: "اقتراحات", en: "Suggestions" },
  contextPanel: { ar: "اللي مساري عارفه عنك", en: "What Masari knows" },
  sourcesUsed: { ar: "المصادر المستخدمة", en: "Sources used" },
  chatWelcome: {
    ar: "أنا مساري، مرشدك الأكاديمي. اسألني عن اللائحة، ساعاتك، أو خطة تخرجك.",
    en: "I'm Masari, your academic advisor. Ask me about the regulations, your credit hours, or your graduation plan.",
  },
  newChat: { ar: "محادثة جديدة", en: "New chat" },
  ragSources: { ar: "المصادر اللي اتبحث فيها", en: "Sources searched" },
  chatError: {
    ar: "مساري مش قادر يرد دلوقتي. اتأكد إن خدمة الـ AI شغالة وجرب تاني كمان شوية.",
    en: "Masari can't answer right now. Make sure the AI service is running and try again shortly.",
  },

  // Recommendations
  recTitle: { ar: "توصيات المقررات والمحاضرين", en: "Course & instructor recommendations" },
  recSubtitle: {
    ar: "بنستبعد الأول المقررات غير المسموح بيها، وبعدين نرتب الباقي حسب مناسبتها ليك.",
    en: "Ineligible courses are filtered out first, then the rest are ranked by how well they suit you.",
  },
  tabCourses: { ar: "المقررات", en: "Courses" },
  tabInstructors: { ar: "المحاضرون", en: "Instructors" },
  selectedLoad: { ar: "الحمل المختار", en: "Selected load" },
  loadOk: { ar: "داخل الحد المسموح", en: "Within the allowed limit" },
  loadOver: { ar: "تجاوز الحد المسموح", en: "Exceeds the allowed limit" },
  rank: { ar: "الترتيب", en: "Rank" },
  priority: { ar: "الأولوية", en: "Priority" },
  unlocks: { ar: "يفتح", en: "Unlocks" },
  coursesWord: { ar: "مقررات", en: "courses" },
  prereqsMet: { ar: "المتطلبات السابقة مستوفاة", en: "Prerequisites met" },
  whyRecommended: { ar: "ليه بنرشحه؟", en: "Why recommended?" },
  addToPlan: { ar: "إضافة للجدول", en: "Add to schedule" },
  added: { ar: "مضاف", en: "Added" },
  notEligible: { ar: "غير مؤهل حاليًا", en: "Not eligible yet" },
  missingPrereq: { ar: "متطلب ناقص", en: "Missing prerequisite" },
  seats: { ar: "مقاعد", en: "seats" },
  full: { ar: "مكتمل", en: "Full" },
  requestSeat: { ar: "طلب فتح مقعد", en: "Request a seat" },
  forCourse: { ar: "المقرر", en: "Course" },
  compatibility: { ar: "التوافق معك", en: "Compatibility with you" },
  yourPreferences: { ar: "تفضيلاتك", en: "Your preferences" },
  prefsHint: {
    ar: "غيّر التفضيلات وشوف الترتيب بيتغير إزاي.",
    en: "Adjust your preferences and watch the ranking update.",
  },
  demoScoring: {
    ar: "حساب توضيحي مؤقت، هيتبدل بنموذج التوافق الفعلي.",
    en: "Placeholder scoring. To be replaced by the trained compatibility model.",
  },
  youPrefer: { ar: "تفضيلك", en: "Your preference" },
  limitedData: {
    ar: "البيانات محدودة، فخد التوصية دي بحذر.",
    en: "Limited data. Treat this suggestion with caution.",
  },
  bestMatch: { ar: "الأنسب ليك", en: "Best match" },
  prefPace: { ar: "سرعة الشرح المفضلة", en: "Preferred teaching pace" },
  prefWorkload: { ar: "العبء اللي تقدر تتحمله", en: "Workload you can handle" },
  prefPractical: { ar: "عملي ولا نظري", en: "Practical or theoretical" },
  slow: { ar: "هادية", en: "Slow" },
  fast: { ar: "سريعة", en: "Fast" },
  light: { ar: "خفيف", en: "Light" },
  heavy: { ar: "تقيل", en: "Heavy" },
  theoretical: { ar: "نظري", en: "Theoretical" },
  practical: { ar: "عملي", en: "Practical" },
  sectionSeats: { ar: "المقاعد حسب السكشن", en: "Seats by section" },
  scoreOutOf: { ar: "درجة الأولوية من 100", en: "Priority score out of 100" },
  section: { ar: "سكشن", en: "Section" },

  // Plan
  planTitle: { ar: "خطة التخرج", en: "Graduation plan" },
  planSubtitle: {
    ar: "خطة مقترحة للفصول الجاية، متحققة من المتطلبات السابقة وحدود الساعات.",
    en: "A proposed multi-semester plan, checked against prerequisites and credit limits.",
  },
  whatIf: { ar: "ماذا لو؟", en: "What if?" },
  whatIfDesc: {
    ar: "جرّب سيناريو وشوف تأثيره على خطتك وموعد تخرجك.",
    en: "Try a scenario and see its impact on your plan and graduation date.",
  },
  baseline: { ar: "الخطة الحالية", en: "Current plan" },
  scenario: { ar: "السيناريو", en: "Scenario" },
  impact: { ar: "التأثير", en: "Impact" },
  affected: { ar: "مقررات متأثرة", en: "Affected courses" },
  electives: { ar: "متابعة الاختياري", en: "Elective tracking" },
  semesterLoad: { ar: "حمل الفصل", en: "Semester load" },
  requires: { ar: "يتطلب", en: "Requires" },
  delayed: { ar: "اتأخر", en: "Delayed" },
  movedEarlier: { ar: "اتقدّم", en: "Moved earlier" },
  noChange: { ar: "بدون تغيير", en: "No change" },
  reset: { ar: "رجوع للخطة الحالية", en: "Reset to current plan" },
  underMinLoad: {
    ar: "أقل من الحد الأدنى (12 ساعة). مسموح بس في ترم التخرج أو بموافقة المجلس.",
    en: "Below the 12-credit minimum. Allowed only in the graduation semester or with council approval.",
  },
  noCoursesThisTerm: { ar: "مفيش مقررات متاحة الترم ده حسب الخطة.", en: "No courses available this semester under the plan." },
  gradTarget: { ar: "عايز تتخرج في قد إيه؟", en: "When do you want to graduate?" },
  gradTargetDesc: {
    ar: "اختار هدفك، والخطة بتتبني من وضعك الحالي على قواعد اللائحة.",
    en: "Pick a target; the plan is built from where you are now, under the regulations.",
  },
  years4: { ar: "٤ سنين", en: "4 years" },
  years45: { ar: "٤ سنين ونص", en: "4.5 years" },
  years5: { ar: "٥ سنين", en: "5 years" },
  regulationPlan: { ar: "خطة اللائحة", en: "Regulation plan" },
  allowSummer: { ar: "أقدر أحضر ترم صيفي", en: "I can attend summer semesters" },
  allowSummerHint: {
    ar: "الصيفي بيتفتح فيه المواد حسب طلب الطلاب، فمواده في الخطة مش مضمونة.",
    en: "Summer courses open on student demand, so summer courses in the plan are not guaranteed.",
  },
  possible: { ar: "ممكن", en: "Possible" },
  notPossible: { ar: "مش ممكن", en: "Not possible" },
  earliestShort: { ar: "أقرب تخرج", en: "Earliest" },
  ifIFail: { ar: "لو سقطت في", en: "If I fail" },
  ifIFailHint: { ar: "مواد الترم الحالي. تقدر تختار أكتر من مادة.", en: "This semester's courses. You can pick more than one." },
  pickCourses: { ar: "اختار المواد", en: "Pick courses" },
  termGpaLabel: { ar: "معدلي الترم ده", en: "My GPA this semester" },
  termGpaHint: { ar: "من 0 لـ 4. بيحدد حد الساعات في الترمات الجاية.", en: "0 to 4. It sets your credit limit for the coming semesters." },
  termGpaPlaceholder: { ar: "مثلًا 2.8", en: "e.g. 2.8" },
  afterThisTerm: { ar: "بعد الترم ده", en: "After this semester" },
  cumulativeGpa: { ar: "المعدل التراكمي", en: "Cumulative GPA" },
  creditCap: { ar: "حد الساعات", en: "Credit limit" },
  probationCap: { ar: "تحت الإنذار", en: "Academic warning" },
  comparedToPlan: { ar: "مقارنة بخطتك من غير السيناريو", en: "Compared with your plan without the scenario" },
  sameGraduation: { ar: "نفس ميعاد التخرج", en: "Same graduation semester" },
  graduationMoves: { ar: "التخرج اتأخر", en: "Graduation moves" },
  summerTerm: { ar: "ترم صيفي", en: "Summer semester" },
  flagSummer: { ar: "لو اتفتحت في الصيفي", en: "If opened in summer" },
  flagTrainingSummer: { ar: "تدريب صيفي", en: "Summer training" },
  flagCollegeRequest: { ar: "بموافقة الكلية", en: "College approval" },
  flagGraduationRequest: { ar: "طلب تخرج للكلية", en: "Graduation request" },
  flagSummerHint: {
    ar: "الكلية بتفتح مواد الصيفي لو عدد كفاية من الطلاب طلبها (بحد أقصى 3 مواد للطالب).",
    en: "The college opens summer courses when enough students request them (up to 3 courses per student).",
  },
  flagCollegeRequestHint: {
    ar: "التدريب مكانه الصيفي، والكلية ممكن تسمح بتسجيله في ترم أساسي.",
    en: "Training belongs in summer; the college can allow it in a main semester.",
  },
  flagGraduationRequestHint: {
    ar: "المادة مش في ترمها، بس الكلية بتفتحها لطالب محتاجها عشان يتخرج الترم ده.",
    en: "Not this course's semester, but the college opens it for a student who needs it to graduate this semester.",
  },
  planLegend: { ar: "معاني العلامات", en: "What the tags mean" },
  planLoading: { ar: "بنحسب خطتك…", en: "Building your plan…" },
  planServiceDown: {
    ar: "خدمة الخطة مش متاحة دلوقتي. جرّب تاني بعد شوية.",
    en: "The plan service is unavailable right now. Try again shortly.",
  },
  retry: { ar: "حاول تاني", en: "Try again" },
  planAssumptionsTitle: { ar: "الخطة مبنية على", en: "The plan assumes" },
  summerCoursesCount: { ar: "مواد صيفي", en: "Summer courses" },
  collegeRequestsCount: { ar: "طلبات للكلية", en: "College requests" },
  graduateThisTerm: { ar: "لو نجحت في مواد الترم ده هتتخرج في آخره.", en: "Pass this semester's courses and you graduate at its end." },

  // Course catalog
  navCatalog: { ar: "دليل المقررات", en: "Course catalog" },
  navCatalogShort: { ar: "الدليل", en: "Catalog" },
  navChatShort: { ar: "اسأل", en: "Ask" },
  navCoursesShort: { ar: "التوصيات", en: "For you" },
  navPlanShort: { ar: "الخطة", en: "Plan" },
  mainNav: { ar: "التنقل الرئيسي", en: "Main navigation" },
  pathTitle: { ar: "مسارك للتخرج", en: "Your path to graduation" },
  pathAria: {
    ar: "مسارك: الفصول المكتملة، ثم الأترام المخططة لحد التخرج.",
    en: "Your path: completed semesters, then planned semesters up to graduation.",
  },
  graduation: { ar: "التخرج", en: "Graduation" },
  pathEmpty: { ar: "ترم فاضي", en: "Empty semester" },
  youAreHere: { ar: "إنت هنا", en: "You are here" },
  semShort: { ar: "الفصل", en: "Sem" },
  pathSwipe: { ar: "اسحب يمين وشمال عشان تشوف كل الفصول", en: "Swipe sideways to see every semester" },
  pathHasFail: { ar: "فصل فيه رسوب", en: "Semester with a failed course" },
  pathLegendDone: { ar: "فصل مكتمل", en: "Completed semester" },
  pathLegendSummer: { ar: "ترم صيفي (لو الكلية فتحت المواد)", en: "Summer semester (if the college opens the courses)" },
  summerShort: { ar: "صيفي", en: "Summer" },
  pathTarget: { ar: "الهدف", en: "Target" },
  pathTargetNotPossible: { ar: "مش ممكن، وده أقرب تخرج", en: "not possible; showing the earliest graduation" },
  pathChangeTarget: { ar: "غيّر الهدف", en: "Change target" },
  pathLegendPlanned: { ar: "ترم مخطط", en: "Planned semester" },
  standing: { ar: "موقفك الأكاديمي", en: "Academic standing" },
  studentProfile: { ar: "ملف الطالب", en: "Student profile" },
  signOut: { ar: "تسجيل الخروج", en: "Sign out" },

  // Login (access code = the student's ID)
  loginTitle: { ar: "ادخل بكود الدخول", en: "Sign in with your access code" },
  loginSub: { ar: "اكتب كود الدخول (رقم الطالب) عشان تفتح مسارك.", en: "Enter your access code (your student ID) to open your path." },
  loginLabel: { ar: "كود الدخول", en: "Access code" },
  loginCta: { ar: "دخول", en: "Sign in" },
  loginChecking: { ar: "بنتحقق من الكود…", en: "Checking your code…" },
  loginErrEmpty: { ar: "اكتب الكود الأول.", en: "Enter your code first." },
  loginErrShort: { ar: "الكود 9 أرقام.", en: "The code has 9 digits." },
  loginErrWrong: { ar: "الكود ده مش صحيح. راجعه وجرّب تاني.", en: "That code isn't valid. Check it and try again." },
  loginWelcome: { ar: "أهلاً يا", en: "Welcome," },
  loginOkSub: { ar: "الكود صحيح. بنفتحلك مسارك…", en: "Code accepted. Opening your path…" },
  loginPersonal: { ar: "الكود شخصي، متشاركهوش مع حد.", en: "Your code is personal. Don't share it." },
  loginDemoHint: { ar: "للتجربة:", en: "For the demo:" },
  loginDemoFill: { ar: "اضغط على الكود عشان يتكتب", en: "Click the code to fill it in" },
  loginFooter: { ar: "مساري · نموذج تجريبي ببيانات محاكاة", en: "Masari · prototype with simulated data" },
  skipToContent: { ar: "تخطي للمحتوى", en: "Skip to content" },
  switchLangLabel: { ar: "التبديل للإنجليزية", en: "Switch to Arabic" },
  catalogTitle: { ar: "دليل مقررات هندسة الذكاء الاصطناعي", en: "AI Engineering course catalog" },
  catalogSubtitle: {
    ar: "كل مقررات البرنامج ومتطلباتها السابقة، ومعاها حالتك في كل مقرر.",
    en: "Every course in the program with its prerequisites, plus your status in each.",
  },
  tabCatalogCourses: { ar: "المقررات والمتطلبات", en: "Courses & prerequisites" },
  tabRegulations: { ar: "اللائحة", en: "Regulations" },
  statTotalCredits: { ar: "إجمالي الساعات", en: "Total credits" },
  statCourses: { ar: "مقرر في الخطة", en: "Courses in the plan" },
  statElectiveSlots: { ar: "خانات اختياري", en: "Elective slots" },
  statSemesters: { ar: "فصول دراسية", en: "Semesters" },
  universityReq: { ar: "متطلبات جامعة", en: "University req." },
  collegeReq: { ar: "متطلبات كلية", en: "College req." },
  specializationReq: { ar: "متطلبات تخصص", en: "Specialization" },
  perBylaws: { ar: "حسب اللائحة", en: "Per the bylaws" },
  search: { ar: "بحث", en: "Search" },
  searchPlaceholder: { ar: "كود أو اسم المقرر…", en: "Code or course name…" },
  levelLabel: { ar: "المستوى", en: "Level" },
  semesterLabel: { ar: "الفصل", en: "Semester" },
  departmentLabel: { ar: "القسم", en: "Department" },
  typeLabel: { ar: "النوع", en: "Type" },
  termLabel: { ar: "الترم", en: "Semester" },
  statusLabel: { ar: "حالتي", en: "My status" },
  all: { ar: "الكل", en: "All" },
  fall: { ar: "خريف", en: "Fall" },
  spring: { ar: "ربيع", en: "Spring" },
  stPassed: { ar: "ناجح", en: "Passed" },
  stFailed: { ar: "راسب", en: "Failed" },
  stEligible: { ar: "مؤهل", en: "Eligible" },
  stLocked: { ar: "مقفول", en: "Locked" },
  resetFilters: { ar: "مسح الفلاتر", en: "Reset filters" },
  showing: { ar: "عرض", en: "Showing" },
  noResults: { ar: "مفيش مقررات مطابقة للفلاتر دي.", en: "No courses match these filters." },
  prerequisites: { ar: "المتطلبات السابقة", en: "Prerequisites" },
  none: { ar: "لا يوجد", en: "None" },
  requiredBy: { ar: "متطلب سابق لـ", en: "Prerequisite for" },
  slotOptions: { ar: "المقررات المتاحة للخانة دي", en: "Courses for this slot" },
  yourPick: { ar: "اختيارك", en: "Your pick" },
  minEarned: { ar: "ساعة مكتسبة على الأقل", en: "earned credits minimum" },
  short: { ar: "ناقص", en: "Short by" },
  details: { ar: "التفاصيل", en: "Details" },
  colCode: { ar: "الكود", en: "Code" },
  colName: { ar: "المقرر", en: "Course" },
  statusHint: {
    ar: "حالتك محسوبة بمحرك القواعد من سجلك (طالب تجريبي).",
    en: "Your status is computed by the rules engine from your record (demo student).",
  },
  catalogSource: {
    ar: "المصدر: دليل برنامج AIE، وهو ملخص غير رسمي للائحة. راجع اللائحة الرسمية قبل الاعتماد عليه.",
    en: "Source: the AIE Program Guide, an unofficial summary of the bylaws. Check the official bylaws before relying on it.",
  },
  yourLimit: { ar: "حدّك", en: "Your limit" },
  gradeScaleTitle: { ar: "نظام التقديرات", en: "Grading scale" },
  gradeCol: { ar: "التقدير", en: "Grade" },
  pointsCol: { ar: "النقاط", en: "Points" },
  assessmentTitle: { ar: "توزيع الدرجات", en: "Grade distribution" },
} satisfies Record<string, L>

export type DictKey = keyof typeof dict

type I18nContextValue = {
  lang: Lang
  dir: "rtl" | "ltr"
  setLang: (l: Lang) => void
  t: (key: DictKey) => string
  tr: (value: L) => string
  num: (n: number, opts?: Intl.NumberFormatOptions) => string
}

const I18nContext = React.createContext<I18nContextValue | null>(null)
const useStoredLang = createStoredValue<Lang>("masari.lang", "ar", (v): v is Lang => v === "ar" || v === "en")

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useStoredLang()

  React.useEffect(() => {
    const el = document.documentElement
    el.lang = lang
    el.dir = lang === "ar" ? "rtl" : "ltr"
    // The pre-paint script in layout.tsx hides the Arabic prerender while English loads.
    if (lang === "en") el.removeAttribute("data-lang-pending")
  }, [lang])

  const value = React.useMemo<I18nContextValue>(() => {
    // Western digits in both languages, matching common usage in Egyptian university records.
    const locale = lang === "ar" ? "ar-EG-u-nu-latn" : "en-US"
    return {
      lang,
      dir: lang === "ar" ? "rtl" : "ltr",
      setLang,
      t: (key) => dict[key][lang],
      tr: (v) => v[lang],
      num: (n, opts) => new Intl.NumberFormat(locale, opts).format(n),
    }
  }, [lang, setLang])

  return (
    <I18nContext.Provider value={value}>
      {/* Tells Base UI components (slider, menus, tabs) which way to read. */}
      <DirectionProvider direction={value.dir}>{children}</DirectionProvider>
    </I18nContext.Provider>
  )
}

export function useI18n() {
  const ctx = React.useContext(I18nContext)
  if (!ctx) throw new Error("useI18n must be used inside <I18nProvider>")
  return ctx
}
